"""subscription

Revision ID: 004a76bbb322
Revises: ac558998f528
Create Date: 2019-09-04 14:44:59.148923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '004a76bbb322'
down_revision = 'ac558998f528'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription',
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('addr', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('num')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription')
    # ### end Alembic commands ###
