"""v2ray_config table

Revision ID: 53db67ad1444
Revises: 
Create Date: 2019-09-04 10:38:36.813534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53db67ad1444'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('v2ray_config',
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('addr', sa.String(length=100), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('uuid', sa.String(length=100), nullable=True),
    sa.Column('alterId', sa.Integer(), nullable=True),
    sa.Column('encrypt', sa.String(length=100), nullable=True),
    sa.Column('trans', sa.String(length=100), nullable=True),
    sa.Column('fake', sa.String(length=100), nullable=True),
    sa.Column('host', sa.String(length=100), nullable=True),
    sa.Column('path', sa.String(length=100), nullable=True),
    sa.Column('tls', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('remarks', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('num')
    )
    op.create_index(op.f('ix_v2ray_config_addr'), 'v2ray_config', ['addr'], unique=False)
    op.create_index(op.f('ix_v2ray_config_remarks'), 'v2ray_config', ['remarks'], unique=False)
    op.create_index(op.f('ix_v2ray_config_status'), 'v2ray_config', ['status'], unique=False)
    op.create_index(op.f('ix_v2ray_config_uuid'), 'v2ray_config', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_v2ray_config_uuid'), table_name='v2ray_config')
    op.drop_index(op.f('ix_v2ray_config_status'), table_name='v2ray_config')
    op.drop_index(op.f('ix_v2ray_config_remarks'), table_name='v2ray_config')
    op.drop_index(op.f('ix_v2ray_config_addr'), table_name='v2ray_config')
    op.drop_table('v2ray_config')
    # ### end Alembic commands ###
