"""v2ray_config

Revision ID: 735546ec32c4
Revises: 5c9c1cd1380a
Create Date: 2019-09-07 12:34:31.318767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '735546ec32c4'
down_revision = '5c9c1cd1380a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('v2ray_config', sa.Column('encrypt', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('v2ray_config', 'encrypt')
    # ### end Alembic commands ###
