"""v2ray_config table

Revision ID: ac558998f528
Revises: 53db67ad1444
Create Date: 2019-09-04 10:45:21.735752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac558998f528'
down_revision = '53db67ad1444'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('v2ray_config', sa.Column('mux', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('v2ray_config', 'mux')
    # ### end Alembic commands ###
