"""v2ray_config

Revision ID: cad6e222547b
Revises: 004a76bbb322
Create Date: 2019-09-05 08:55:20.594982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cad6e222547b'
down_revision = '004a76bbb322'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('v2ray_config', sa.Column('sub', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('v2ray_config', 'sub')
    # ### end Alembic commands ###
